# core/Dockerfile.worker

FROM python:3.12-slim

RUN apt-get update && apt-get install -y \
    gcc libpq-dev \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

RUN adduser --disabled-password --gecos "" workeruser
USER workeruser

# Worker Celery (sin puerto expuesto)
CMD ["celery", "-A", "workers.celery_app", "worker", \
     "--loglevel=info", "--concurrency=2", "-Q", "synthesis,challenges,perception"]
