port 26379
dir /tmp
sentinel monitor greedylm-master redis-master 6379 2
sentinel down-after-milliseconds greedylm-master 5000
sentinel failover-timeout greedylm-master 60000
sentinel parallel-syncs greedylm-master 1
bind 0.0.0.0
protected-mode no
