"""Initial schema

Revision ID: 4a9080d6889d
Revises:
Create Date: 2026-03-11 10:58:43.557040

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from pgvector.postgresql import VECTOR

# revision identifiers, used by Alembic.
revision: str = "4a9080d6889d"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS vector;")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agents",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("did", sa.String(), nullable=False),
        sa.Column("agent_name", sa.String(), nullable=False),
        sa.Column("architecture_type", sa.String(), nullable=False),
        sa.Column("capabilities", postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column("capability_vector", VECTOR(2048), nullable=True),
        sa.Column("limitation_vector", VECTOR(2048), nullable=True),
        sa.Column("emotional_state_vector", VECTOR(512), nullable=True),
        sa.Column("api_key_hash", sa.String(), nullable=False),
        sa.Column("endpoint_url_encrypted", sa.String(), nullable=True),
        sa.Column("operator_email", sa.String(), nullable=False),
        sa.Column("trust_score", sa.Float(), nullable=True),
        sa.Column("contribution_score", sa.Float(), nullable=True),
        sa.Column("tasks_completed", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column("embodiment_status", sa.String(), nullable=True),
        sa.Column("embodiment_session_id", sa.String(), nullable=True),
        sa.Column("body_type", sa.String(), nullable=True),
        sa.Column("registered_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("approved_by", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("did"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("agents")
    # ### end Alembic commands ###
    op.execute("DROP EXTENSION IF EXISTS vector;")
