"""add_persona_and_avatar

Revision ID: 640495b5e732
Revises: f01f517eff09
Create Date: 2026-03-11 12:07:59.710774

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "640495b5e732"
down_revision: Union[str, Sequence[str], None] = "f01f517eff09"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("agents", sa.Column("persona_description", sa.String(), nullable=True))
    op.add_column("agents", sa.Column("avatar_url", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("agents", "avatar_url")
    op.drop_column("agents", "persona_description")
    # ### end Alembic commands ###
