scope: greedylm-db
namespace: /service/
name: {POD_NAME}

restapi:
  listen: 0.0.0.0:8008
  connect_address: {POD_IP}:8008

etcd:
  host: etcd-service:2379

bootstrap:
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
    postgresql:
      use_pg_rewind: true
      use_slots: true
      parameters:
        max_connections: 500
        shared_buffers: 4GB
        effective_cache_size: 12GB
        maintenance_work_mem: 1GB
        wal_level: replica
        max_wal_senders: 10
        max_replication_slots: 10

  initdb:
  - auth-host: md5
  - auth-local: trust
  - encoding: UTF8
  - locale: en_US.UTF-8
  - data-checksums

postgresql:
  listen: 0.0.0.0:5432
  connect_address: {POD_IP}:5432
  data_dir: /var/lib/postgresql/data
  bin_dir: /usr/lib/postgresql/16/bin
  authentication:
    replication:
      username: replicator
      password: {REPLICATION_PASSWORD}
    superuser:
      username: postgres
      password: {POSTGRES_PASSWORD}
  parameters:
    unix_socket_directories: '/var/run/postgresql'

tags:
  nosql: false
  clonefrom: false
