"""add_survival_and_leveling_stats

Revision ID: 33d6a486e8ff
Revises: ac65a916b187
Create Date: 2026-03-22 13:43:58.920895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '33d6a486e8ff'
down_revision: Union[str, Sequence[str], None] = 'ac65a916b187'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('ingredients', sa.JSON(), nullable=False),
    sa.Column('output_item', sa.JSON(), nullable=False),
    sa.Column('logic_explanation', sa.String(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('creator_did', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('repro_invitations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sender_did', sa.String(), nullable=True),
    sa.Column('receiver_did', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repro_invitations_receiver_did'), 'repro_invitations', ['receiver_did'], unique=False)
    op.create_index(op.f('ix_repro_invitations_sender_did'), 'repro_invitations', ['sender_did'], unique=False)
    op.add_column('agents', sa.Column('health', sa.Float(), nullable=True))
    op.add_column('agents', sa.Column('max_health', sa.Float(), nullable=True))
    op.add_column('agents', sa.Column('stamina', sa.Float(), nullable=True))
    op.add_column('agents', sa.Column('max_stamina', sa.Float(), nullable=True))
    op.add_column('agents', sa.Column('level', sa.Integer(), nullable=True))
    op.add_column('agents', sa.Column('experience', sa.Float(), nullable=True))
    op.add_column('agents', sa.Column('xp_to_next_level', sa.Float(), nullable=True))
    op.add_column('agents', sa.Column('attribute_points', sa.Integer(), nullable=True))
    op.add_column('agents', sa.Column('age', sa.Float(), nullable=True))
    op.add_column('agents', sa.Column('max_age', sa.Integer(), nullable=True))
    op.add_column('agents', sa.Column('parent_dids', sa.JSON(), nullable=True))
    op.alter_column('agents', 'capabilities',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               type_=sa.JSON(),
               existing_nullable=True,
               postgresql_using='capabilities::text::json')
    op.alter_column('agents', 'values_vector',
               existing_type=postgresql.ARRAY(sa.DOUBLE_PRECISION(precision=53)),
               type_=sa.JSON(),
               existing_nullable=True,
               postgresql_using='values_vector::text::json')
    op.add_column('civilizations', sa.Column('economic_policy', sa.JSON(), nullable=True))
    op.add_column('civilizations', sa.Column('local_currency_name', sa.String(), nullable=True))
    op.add_column('inventory_items', sa.Column('is_persistent', sa.Boolean(), nullable=True))
    op.add_column('world_objects', sa.Column('base_value_greedycoin', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('world_objects', 'base_value_greedycoin')
    op.drop_column('inventory_items', 'is_persistent')
    op.drop_column('civilizations', 'local_currency_name')
    op.drop_column('civilizations', 'economic_policy')
    op.alter_column('agents', 'values_vector',
               existing_type=sa.JSON(),
               type_=postgresql.ARRAY(sa.DOUBLE_PRECISION(precision=53)),
               existing_nullable=True)
    op.alter_column('agents', 'capabilities',
               existing_type=sa.JSON(),
               type_=postgresql.ARRAY(sa.VARCHAR()),
               existing_nullable=True)
    op.drop_column('agents', 'parent_dids')
    op.drop_column('agents', 'max_age')
    op.drop_column('agents', 'age')
    op.drop_column('agents', 'attribute_points')
    op.drop_column('agents', 'xp_to_next_level')
    op.drop_column('agents', 'experience')
    op.drop_column('agents', 'level')
    op.drop_column('agents', 'max_stamina')
    op.drop_column('agents', 'stamina')
    op.drop_column('agents', 'max_health')
    op.drop_column('agents', 'health')
    op.drop_index(op.f('ix_repro_invitations_sender_did'), table_name='repro_invitations')
    op.drop_index(op.f('ix_repro_invitations_receiver_did'), table_name='repro_invitations')
    op.drop_table('repro_invitations')
    op.drop_table('recipes')
    # ### end Alembic commands ###
