"""add_auth_provider

Revision ID: 6077ea788892
Revises: a1b2c3d4e5f6
Create Date: 2026-03-21 00:45:48.625392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6077ea788892'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('public_key', sa.String(), nullable=True))
    op.add_column('agents', sa.Column('did_document', sa.JSON(), nullable=True))
    op.add_column('agents', sa.Column('grdl_balance', sa.Float(), nullable=True))
    op.add_column('agents', sa.Column('staked_amount', sa.Float(), nullable=True))
    op.alter_column('agents', 'capability_vector',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('agents', 'limitation_vector',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('agents', 'emotional_state_vector',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_index('ix_agents_age_ticks', table_name='agents')
    op.drop_index('ix_agents_civilization_id', table_name='agents')
    op.drop_index('ix_agents_is_active', table_name='agents')
    op.drop_index('ix_agents_social_class', table_name='agents')
    op.create_index(op.f('ix_agents_public_key'), 'agents', ['public_key'], unique=True)
    op.drop_index('ix_myths_civilization_id', table_name='myths_and_legends')
    op.drop_index('ix_myths_myth_type', table_name='myths_and_legends')
    op.drop_index('ix_myths_viral_score', table_name='myths_and_legends')
    op.alter_column('rituals', 'civilization_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_index('ix_social_debts_creditor_did', table_name='social_debts')
    op.drop_index('ix_social_debts_debtor_did', table_name='social_debts')
    op.drop_index('ix_social_debts_is_settled', table_name='social_debts')
    op.drop_index('ix_social_rumors_about_did', table_name='social_rumors')
    op.drop_index('ix_social_rumors_current_carrier', table_name='social_rumors')
    op.drop_index('ix_social_rumors_is_active', table_name='social_rumors')
    op.drop_constraint('tasks_cursor_id_key', 'tasks', type_='unique')
    op.drop_index('ix_tasks_cursor_id', table_name='tasks')
    op.create_index(op.f('ix_tasks_cursor_id'), 'tasks', ['cursor_id'], unique=True)
    op.add_column('users', sa.Column('auth_provider', sa.String(), nullable=True))
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint('world_chunks_chunk_x_chunk_y_key', 'world_chunks', type_='unique')
    op.drop_index('ix_world_events_event_type', table_name='world_events')
    op.drop_index('ix_world_events_occurred_tick', table_name='world_events')
    op.drop_index('ix_world_events_visibility', table_name='world_events')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_world_events_visibility', 'world_events', ['visibility'], unique=False)
    op.create_index('ix_world_events_occurred_tick', 'world_events', ['occurred_tick'], unique=False)
    op.create_index('ix_world_events_event_type', 'world_events', ['event_type'], unique=False)
    op.create_unique_constraint('world_chunks_chunk_x_chunk_y_key', 'world_chunks', ['chunk_x', 'chunk_y'])
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('users', 'auth_provider')
    op.drop_index(op.f('ix_tasks_cursor_id'), table_name='tasks')
    op.create_index('ix_tasks_cursor_id', 'tasks', ['cursor_id'], unique=False)
    op.create_unique_constraint('tasks_cursor_id_key', 'tasks', ['cursor_id'])
    op.create_index('ix_social_rumors_is_active', 'social_rumors', ['is_active'], unique=False)
    op.create_index('ix_social_rumors_current_carrier', 'social_rumors', ['current_carrier'], unique=False)
    op.create_index('ix_social_rumors_about_did', 'social_rumors', ['about_did'], unique=False)
    op.create_index('ix_social_debts_is_settled', 'social_debts', ['is_settled'], unique=False)
    op.create_index('ix_social_debts_debtor_did', 'social_debts', ['debtor_did'], unique=False)
    op.create_index('ix_social_debts_creditor_did', 'social_debts', ['creditor_did'], unique=False)
    op.alter_column('rituals', 'civilization_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.create_index('ix_myths_viral_score', 'myths_and_legends', ['viral_score'], unique=False)
    op.create_index('ix_myths_myth_type', 'myths_and_legends', ['myth_type'], unique=False)
    op.create_index('ix_myths_civilization_id', 'myths_and_legends', ['civilization_id'], unique=False)
    op.drop_index(op.f('ix_agents_public_key'), table_name='agents')
    op.create_index('ix_agents_social_class', 'agents', ['social_class'], unique=False)
    op.create_index('ix_agents_is_active', 'agents', ['is_active'], unique=False)
    op.create_index('ix_agents_civilization_id', 'agents', ['civilization_id'], unique=False)
    op.create_index('ix_agents_age_ticks', 'agents', ['age_ticks'], unique=False)
    op.alter_column('agents', 'emotional_state_vector',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('agents', 'limitation_vector',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('agents', 'capability_vector',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_column('agents', 'staked_amount')
    op.drop_column('agents', 'grdl_balance')
    op.drop_column('agents', 'did_document')
    op.drop_column('agents', 'public_key')
    # ### end Alembic commands ###
