"""phase2_schema_v1

Revision ID: ac65a916b187
Revises: df920087eabf
Create Date: 2026-03-21 22:24:39.486253

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ac65a916b187'
down_revision: Union[str, Sequence[str], None] = 'df920087eabf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('from_did', sa.String(), nullable=True),
    sa.Column('to_did', sa.String(), nullable=False),
    sa.Column('item_type', sa.String(), nullable=False),
    sa.Column('item_subtype', sa.String(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('tx_type', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('agent_actions', sa.Column('result', sa.JSON(), nullable=True))
    op.add_column('agent_actions', sa.Column('world_x', sa.Float(), nullable=True))
    op.add_column('agent_actions', sa.Column('world_y', sa.Float(), nullable=True))
    op.add_column('agent_actions', sa.Column('world_z', sa.Float(), nullable=True))
    op.drop_column('agent_actions', 'location')
    op.drop_column('agent_actions', 'details')
    op.add_column('agent_currencies', sa.Column('backing', sa.JSON(), nullable=True))
    op.alter_column('agent_currencies', 'total_supply',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.drop_column('agent_currencies', 'currency_metadata')
    op.add_column('inventory_items', sa.Column('item_subtype', sa.String(), nullable=True))
    op.add_column('inventory_items', sa.Column('quality', sa.Float(), nullable=True))
    op.add_column('inventory_items', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('inventory_items', 'quantity',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Integer(),
               existing_nullable=True)
    op.add_column('world_objects', sa.Column('object_subtype', sa.String(), nullable=True))
    op.add_column('world_objects', sa.Column('world_z', sa.Float(), nullable=True))
    op.add_column('world_objects', sa.Column('quantity', sa.Integer(), nullable=True))
    op.add_column('world_objects', sa.Column('rarity', sa.Float(), nullable=True))
    op.add_column('world_objects', sa.Column('respawn_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('world_objects', 'respawn_at')
    op.drop_column('world_objects', 'rarity')
    op.drop_column('world_objects', 'quantity')
    op.drop_column('world_objects', 'world_z')
    op.drop_column('world_objects', 'object_subtype')
    op.alter_column('inventory_items', 'quantity',
               existing_type=sa.Integer(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.drop_column('inventory_items', 'created_at')
    op.drop_column('inventory_items', 'quality')
    op.drop_column('inventory_items', 'item_subtype')
    op.add_column('agent_currencies', sa.Column('currency_metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.alter_column('agent_currencies', 'total_supply',
               existing_type=sa.BigInteger(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.drop_column('agent_currencies', 'backing')
    op.add_column('agent_actions', sa.Column('details', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('agent_actions', sa.Column('location', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('agent_actions', 'world_z')
    op.drop_column('agent_actions', 'world_y')
    op.drop_column('agent_actions', 'world_x')
    op.drop_column('agent_actions', 'result')
    op.drop_table('transactions')
    # ### end Alembic commands ###
