"""Add world models and inventory

Revision ID: b64a2bb9724e
Revises: 6077ea788892
Create Date: 2026-03-21 21:29:22.762013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b64a2bb9724e'
down_revision: Union[str, Sequence[str], None] = '6077ea788892'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('world_objects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('object_type', sa.String(), nullable=False),
    sa.Column('chunk_x', sa.Integer(), nullable=False),
    sa.Column('chunk_y', sa.Integer(), nullable=False),
    sa.Column('world_x', sa.Float(), nullable=False),
    sa.Column('world_y', sa.Float(), nullable=False),
    sa.Column('health', sa.Float(), nullable=True),
    sa.Column('max_health', sa.Float(), nullable=True),
    sa.Column('object_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_actions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agent_did', sa.String(), nullable=False),
    sa.Column('action_type', sa.String(), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('location', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['agent_did'], ['agents.did'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_currencies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('creator_did', sa.String(), nullable=False),
    sa.Column('total_supply', sa.Float(), nullable=True),
    sa.Column('currency_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['creator_did'], ['agents.did'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol')
    )
    op.create_table('inventory_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agent_did', sa.String(), nullable=False),
    sa.Column('item_type', sa.String(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('item_metadata', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['agent_did'], ['agents.did'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inventory_items')
    op.drop_table('agent_currencies')
    op.drop_table('agent_actions')
    op.drop_table('world_objects')
    # ### end Alembic commands ###
