"""add_user_model

Revision ID: c5438312a758
Revises: 640495b5e732
Create Date: 2026-03-15 17:29:05.277911

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "c5438312a758"
down_revision: Union[str, Sequence[str], None] = "640495b5e732"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    conn = op.get_bind()

    # Create users table only if it doesn't exist
    if not conn.dialect.has_table(conn, "users"):
        op.create_table(
            "users",
            sa.Column("id", sa.UUID(), nullable=False),
            sa.Column("email", sa.String(), nullable=False),
            sa.Column("password_hash", sa.String(), nullable=False),
            sa.Column("role", sa.String(), nullable=True),
            sa.Column("is_active", sa.Boolean(), nullable=True),
            sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
            sa.PrimaryKeyConstraint("id"),
            sa.UniqueConstraint("email"),
        )

    if not conn.dialect.has_table(conn, "penalty_records"):
        op.create_table(
            "penalty_records",
            sa.Column("id", sa.Integer(), nullable=False),
            sa.Column("agent_did", sa.String(), nullable=True),
            sa.Column("reason", sa.String(), nullable=True),
            sa.Column("amount_grdl", sa.Float(), nullable=True),
            sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
            sa.ForeignKeyConstraint(["agent_did"], ["agents.did"]),
            sa.PrimaryKeyConstraint("id"),
        )

    # Penalty records changes — skip if already applied
    try:
        op.add_column("penalty_records", sa.Column("amount_grdl", sa.Float(), nullable=True))
    except Exception:
        pass
    try:
        op.add_column(
            "penalty_records",
            sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        )
    except Exception:
        pass
    try:
        op.alter_column("penalty_records", "agent_did", existing_type=sa.VARCHAR(), nullable=True)
    except Exception:
        pass
    try:
        op.create_foreign_key(None, "penalty_records", "agents", ["agent_did"], ["did"])
    except Exception:
        pass
    try:
        op.drop_column("penalty_records", "penalty_weight")
    except Exception:
        pass
    try:
        op.drop_column("penalty_records", "timestamp")
    except Exception:
        pass


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "penalty_records",
        sa.Column(
            "timestamp",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "penalty_records",
        sa.Column("penalty_weight", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "penalty_records", type_="foreignkey")
    op.alter_column("penalty_records", "agent_did", existing_type=sa.VARCHAR(), nullable=False)
    op.drop_column("penalty_records", "created_at")
    op.drop_column("penalty_records", "amount_grdl")
    op.drop_table("users")
    # ### end Alembic commands ###
