"""Add weight and timed action fields

Revision ID: df920087eabf
Revises: b64a2bb9724e
Create Date: 2026-03-21 21:38:09.353353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df920087eabf'
down_revision: Union[str, Sequence[str], None] = 'b64a2bb9724e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('current_action', sa.String(), nullable=True))
    op.add_column('agents', sa.Column('action_target_id', sa.UUID(), nullable=True))
    op.add_column('agents', sa.Column('action_finish_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('agents', sa.Column('max_inventory_weight', sa.Float(), nullable=True))
    op.add_column('inventory_items', sa.Column('weight_kg', sa.Float(), nullable=True))
    op.add_column('world_objects', sa.Column('weight_kg', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('world_objects', 'weight_kg')
    op.drop_column('inventory_items', 'weight_kg')
    op.drop_column('agents', 'max_inventory_weight')
    op.drop_column('agents', 'action_finish_at')
    op.drop_column('agents', 'action_target_id')
    op.drop_column('agents', 'current_action')
    # ### end Alembic commands ###
