"""add_attestation_fields

Revision ID: f01f517eff09
Revises: 4a9080d6889d
Create Date: 2026-03-11 11:52:53.682700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f01f517eff09'
down_revision: Union[str, Sequence[str], None] = '4a9080d6889d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('last_attestation', sa.DateTime(timezone=True), nullable=True))
    op.add_column('agents', sa.Column('integrity_check_passed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agents', 'integrity_check_passed')
    op.drop_column('agents', 'last_attestation')
    # ### end Alembic commands ###
